"""
prepare_data.py
Reads goisco_products.json and outputs data.js for the frontend.
Run AFTER goisco_scraper.py:  python prepare_data.py
"""

import json
import re

INPUT_FILE  = "goisco_products.json"
OUTPUT_FILE = "data.js"

CATEGORY_MAP = {
    "Snacks & Sweets":          "Snacks",
    "Nutrition":                "Gezondheid",
    "Beverages":                "Dranken",
    "Body Care":                "Verzorging",
    "Frozen Foods":             "Diepvries",
    "Alcohol & Tobacco":        "Alcohol",
    "Dairy & Eggs":             "Zuivel & Eieren",
    "Cleaning":                 "Schoonmaak",
    "Laundry":                  "Was & Schoonmaak",
    "Plastic & Foil Supplies":  "Huishouden",
    "Paper Supplies":           "Huishouden",
    "Meat, Chicken & Seafood":  "Vlees & Vis",
    "Fresh Fruits & Vegetables":"Groente & Fruit",
    "Bakery":                   "Brood & Bakkerij",
    "Condiments":               "Sauzen & Kruiden",
    "Breakfast & Spreads":      "Ontbijt",
    "Canned & Jarred Goods":    "Houdbaar",
    "Pasta, Rice & Grains":     "Pasta & Rijst",
    "Baby & Toddler":           "Baby",
    "Pet Supplies":             "Dieren",
    "Electronics":              "Overig",
    "Home & Garden":            "Huishouden",
    "Clothing":                 "Overig",
    "Sports & Outdoors":        "Sport",
    "Toys & Games":             "Overig",
    "Office Supplies":          "Overig",
}

def clean_name(name: str) -> str:
    """Remove size/weight suffixes that make names too long."""
    name = name.strip()
    # Truncate very long names
    if len(name) > 60:
        name = name[:57] + "..."
    return name

def map_category(raw_cat: str) -> str:
    return CATEGORY_MAP.get(raw_cat, raw_cat or "Overig")

def process():
    print(f"Reading {INPUT_FILE}...")
    with open(INPUT_FILE, encoding="utf-8") as f:
        products = json.load(f)

    # Only keep products that are in stock and have a real price
    available = [
        p for p in products
        if p.get("available") and p.get("price_ang", 0) > 0
    ]
    print(f"  Total scraped:    {len(products)}")
    print(f"  In stock:         {len(available)}")

    output = []
    for p in available:
        output.append({
            "id":       p["id"],
            "name":     clean_name(p["name"]),
            "vendor":   p.get("vendor", ""),
            "cat":      map_category(p.get("category", "")),
            "price":    p["price_ang"],
            "sale":     p.get("on_sale", False),
            "compare":  p.get("compare_price_ang"),
            "img":      p.get("image_url", ""),
            "store":    "goisco",
        })

    # Sort by category then name
    output.sort(key=lambda x: (x["cat"], x["name"]))

    # Build the JS file
    js = f"// Auto-generated by prepare_data.py — {len(output)} products from Goisco\n"
    js += "const GOISCO_PRODUCTS = " + json.dumps(output, ensure_ascii=False, indent=2) + ";\n"

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(js)

    # Summary
    cats = {}
    for p in output:
        cats[p["cat"]] = cats.get(p["cat"], 0) + 1

    print(f"\n  Written to {OUTPUT_FILE}: {len(output)} products")
    print(f"\n  Categories:")
    for cat, count in sorted(cats.items(), key=lambda x: -x[1]):
        print(f"    {cat:<28} {count}")

if __name__ == "__main__":
    process()
